version: 2
jobs:
  build:
    machine: # for docker --privileged
      image: circleci/classic:latest
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: Install deps & check project
          command: >
            docker run --mount src=`pwd`,target=/workdir,type=bind \
            --privileged --name nuvolasdk-ci tiliado/nuvolasdk-ci
      - store_artifacts:
          path: ~/workdir/keep
