version: 2
jobs:
  build:
    machine: # for docker --privileged
      image: circleci/classic:latest
    working_directory: ~/workdir
    steps:
      - checkout
      - run:
          name: Pull tiliado/nuvolasdk-ci
          command: docker pull tiliado/nuvolasdk-ci
      - run:
          name: Check project
          command: docker run -v `pwd`:/workdir --privileged tiliado/nuvolasdk-ci
      - store_artifacts:
          path: ~/workdir/keep
